#!/bin/bash
# timeout <seconds> <command...>
#
# Allows <command...> up to <seconds> seconds to complete, 
# else kills the process and issues an ugly abort signal such as e.g.
#    timeout: line 4:  8435 Alarm clock: 14         perl -e 'alarm shift; exec @ARGV' "$@"
#
# Example:
#    timout 300 ./verify ts/qian_fixed.ts crn/crn3.crn 
#
# The function being run can't mess with the clock.  But this works:
#    /usr/bin/time timout 300 ./verify ts/qian_fixed.ts crn/crn2.crn 

doalarm () { perl -e 'alarm shift; exec @ARGV' "$@"; } 

doalarm $@


